#!/bin/bash

FILES=\"$(echo $* | sed 's/ /\",\"/g')\"

echo $FILES

DATA_STR='{"server":{"ip":"localhost","port":54321},"files":['$FILES'],"target":"/home/emiapwil/workspace/alto-plus-fdt/"}'

echo $DATA_STR > tmp

curl -X POST --data-raw $DATA_STR http://localhost:6667/pull
rm -f tmp
