#!/bin/bash

MASTER_IP=$1
SERVER_IP=$2
CLIENT_IP=$3

FILES=\"$(echo $* | sed 's/ /\",\"/g')\"

echo $FILES

CLIENT_INFO='{"hostname":"'$CLIENT_IP'"}'
SERVER_INFO='{"hostname":"'$SERVER_IP'"}'

DATA_STR='{"server":'$CLIENT_INFO',"client":'$CLIENT_INFO',"files":['$FILES'],"target":"/home/emiapwil/workspace/alto-plus-fdt/"}'

curl -X POST --data-raw $DATA_STR 'http://'$MASTER_IP':6665/task/submit'
